// Mock questions - in a real app, these would be generated by AI based on subject
export default [
    {
      id: "q1",
      question: "What is the capital of France?",
      options: [
        { id: "a", text: "London" },
        { id: "b", text: "Paris" },
        { id: "c", text: "Berlin" },
        { id: "d", text: "Madrid" },
      ],
      correctAnswerId: "b",
      difficulty: "easy",
    },
    {
      id: "q2",
      question: "Which planet is known as the Red Planet?",
      options: [
        { id: "a", text: "Venus" },
        { id: "b", text: "Mars" },
        { id: "c", text: "Jupiter" },
        { id: "d", text: "Saturn" },
      ],
      correctAnswerId: "b",
      difficulty: "easy",
    },
    {
      id: "q3",
      question: "What is the largest mammal in the world?",
      options: [
        { id: "a", text: "Elephant" },
        { id: "b", text: "Giraffe" },
        { id: "c", text: "Blue Whale" },
        { id: "d", text: "Polar Bear" },
      ],
      correctAnswerId: "c",
      difficulty: "medium",
    },
    {
      id: "q4",
      question: "Which element has the chemical symbol 'O'?",
      options: [
        { id: "a", text: "Gold" },
        { id: "b", text: "Oxygen" },
        { id: "c", text: "Osmium" },
        { id: "d", text: "Oganesson" },
      ],
      correctAnswerId: "b",
      difficulty: "medium",
    },
    {
      id: "q5",
      question: "Who painted the Mona Lisa?",
      options: [
        { id: "a", text: "Vincent van Gogh" },
        { id: "b", text: "Pablo Picasso" },
        { id: "c", text: "Leonardo da Vinci" },
        { id: "d", text: "Michelangelo" },
      ],
      correctAnswerId: "c",
      difficulty: "hard",
    },
  ];